In [2]:
import pandas as pd
import numpy as np
import datetime

#file_path = '/content/drive/MyDrive/Data Files/Data Files/'  # Path specific to Dennis
file_in = 'Red Light Cameras Data.csv'

In [3]:
file_content = pd.read_csv(file_in,
                           nrows = None,
                           index_col='ID',
                           )
file_content

,_id,INTERSECTION_ID,LINEAR_NAME_FULL_1,LINEAR_NAME_FULL_2,X,Y,LONGITUDE,LATITUDE,OBJECTID,geometry,...,ADDITIONAL_INFO,POLICE_DIVISION_1,WARD_1,WARD_3,WARD_2,WARD_4,NAME,DISTRICT,RLC,MAIN
ID,,,,,,,,,,,,,,,,,,,,,
1,20770,13465959.0,Richmond St E,Parliament St,NaN,NaN,NaN,NaN,1,"{u'type': u'Point', u'coordinates': (-79.36402...",...,NaN,51,Toronto Centre(13),NaN,NaN,NaN,Richmond St E And Parliament St,Toronto and East York,6001,RICHMOND ST E
2,20771,13467993.0,Lake Shore Blvd W,York St,NaN,NaN,NaN,NaN,2,"{u'type': u'Point', u'coordinates': (-79.38086...",...,WB LAKE SHORE BLVD,52,Spadina-Fort York(10),NaN,NaN,NaN,Lake Shore Blvd W And York St,Toronto and East York,6002,LAKE SHORE BLVD W
3,20772,13444656.0,Steeles Ave W,Carpenter Rd,NaN,NaN,NaN,NaN,3,"{u'type': u'Point', u'coordinates': (-79.44758...",...,NaN,32,York Centre(6),NaN,NaN,NaN,Steeles Ave W And Carpenter Rd / Private Acces...,North York,6003,STEELES AVE W
4,20773,13444138.0,Steeles Ave W,Hilda Ave,NaN,NaN,NaN,NaN,4,"{u'type': u'Point', u'coordinates': (-79.42926...",...,NaN,32,Willowdale(18),NaN,NaN,NaN,Steeles Ave W And Hilda Ave,North York,6004,STEELES AVE W
5,20774,13451893.0,Albion Rd,Silverstone Dr,NaN,NaN,NaN,NaN,5,"{u'type': u'Point', u'coordinates': (-79.60009...",...,NaN,23,Etobicoke North(1),NaN,NaN,NaN,Albion Rd And Silverstone Dr,Etobicoke York,6005,ALBION RD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,20959,13445620.0,Steeles Ave W,Alness St,NaN,NaN,NaN,NaN,190,"{u'type': u'Point', u'coordinates': (-79.48105...",...,NaN,32,York Centre(6),NaN,NaN,NaN,Steeles Ave W And Alness St,North York,6224,STEELES AVE W
191,20960,13467918.0,Burnhamthorpe Rd,The West Mall,NaN,NaN,NaN,NaN,191,"{u'type': u'Point', u'coordinates': (-79.56725...",...,NaN,22,Etobicoke Centre(2),NaN,NaN,NaN,Burnhamthorpe Rd And The West Mall,Etobicoke York,6227,BURNHAMTHORPE RD
192,20961,13464218.0,Jane St,St Clair Ave W,NaN,NaN,NaN,NaN,192,"{u'type': u'Point', u'coordinates': (-79.49176...",...,NaN,12,York South-Weston(5),NaN,NaN,NaN,Jane St And St Clair Ave W,Etobicoke York,6230,JANE ST
193,20962,13448022.0,Willowdale Ave,Spring Garden Ave,NaN,NaN,NaN,NaN,193,"{u'type': u'Point', u'coordinates': (-79.40090...",...,NaN,32,Willowdale(18),NaN,NaN,NaN,Willowdale Ave And Spring Garden Ave,North York,6237,WILLOWDALE AVE
194,20963,13448822.0,Markham Rd,Greencedar Crct,NaN,NaN,NaN,NaN,194,"{u'type': u'Point', u'coordinates': (-79.22470...",...,NaN,43,Scarborough-Guildwood(24),NaN,NaN,NaN,Markham Rd And Greencedar Crct / Greencrest Crct,Scarborough,6243,MARKHAM RD

In [11]:
file_content[(file_content['_id']==20823)|(file_content['_id']==20891)][['NAME','MAIN']]

                            NAME      MAIN
ID
54   Keele St And Lawrence Ave W  KEELE ST
122  Keele St And Lawrence Ave W  KEELE ST

In [56]:
file_content.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 194 entries, 1 to 194
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   _id                 194 non-null    int64
 1   INTERSECTION_ID     189 non-null    float64
 2   LINEAR_NAME_FULL_1  189 non-null    object
 3   LINEAR_NAME_FULL_2  189 non-null    object
 4   X                   0 non-null      float64
 5   Y                   0 non-null      float64
 6   LONGITUDE           0 non-null      float64
 7   LATITUDE            0 non-null      float64
 8   OBJECTID            194 non-null    int64
 9   geometry            194 non-null    object
 10  MID_BLOCK           0 non-null      float64
 11  POLICE_DIVISION_2   26 non-null     float64
 12  POLICE_DIVISION_3   1 non-null      float64
 13  ACTIVATION_DATE     194 non-null    object
 14  SIDE2               34 non-null     object
 15  CLIENT_STREET_2     194 non-null    object
 16  CLIENT_STREET_1     194 non-null    object
 17  SIDE1               194 non-null    object
 18  MI_PRINX            194 non-null    int64
 19  PRIVATE_ACCESS      4 non-null      object
 20  TCS                 194 non-null    int64
 21  ADDITIONAL_INFO     6 non-null      object
 22  POLICE_DIVISION_1   194 non-null    int64
 23  WARD_1              194 non-null    object
 24  WARD_3              0 non-null      float64
 25  WARD_2              31 non-null     object
 26  WARD_4              0 non-null      float64
 27  NAME                194 non-null    object
 28  DISTRICT            194 non-null    object
 29  RLC                 194 non-null    int64
 30  MAIN                194 non-null    object
dtypes: float64(10), int64(6), object(15)
memory usage: 48.5+ KB

In [12]:
new = file_content['geometry'].str.split(":",expand=True)
new2=new.iloc[:,2].str.split(",",expand=True)

In [13]:
def longitude(x):
    return x[0][2:]

def latitude(x):
    return x[1][:-2]

def activation_day(x):
    return pd.to_datetime(x['ACTIVATION_DATE'][:10] + ' '+ x['ACTIVATION_DATE'][12:])

In [14]:
lon=new2.apply(longitude,axis=1)
lon.astype(float)

ID
1     -79.364023
2     -79.380868
3     -79.447589
4     -79.429267
5     -79.600094
         ...
190   -79.481057
191   -79.567250
192   -79.491767
193   -79.400906
194   -79.224709
Length: 194, dtype: float64

In [15]:
lat=new2.apply(latitude,axis=1)
lat.astype(float)

ID
1      43.654559
2      43.641460
3      43.792013
4      43.796007
5      43.742952
         ...
190    43.784700
191    43.644552
192    43.667184
193    43.766343
194    43.757840
Length: 194, dtype: float64

In [16]:
file_content['LONGITUDE']=lon
file_content['LATITUDE']=lat

In [17]:
file_content["ACTIVATION_TIME"] = file_content.apply(activation_day,axis=1)

In [18]:
file_content.rename(columns={"_id": "CAMERA_ID"},inplace=True)

In [19]:
red_light=file_content[['CAMERA_ID','INTERSECTION_ID','LINEAR_NAME_FULL_1','LINEAR_NAME_FULL_2','LONGITUDE','LATITUDE','ACTIVATION_TIME']]
red_light

,CAMERA_ID,INTERSECTION_ID,LINEAR_NAME_FULL_1,LINEAR_NAME_FULL_2,LONGITUDE,LATITUDE,ACTIVATION_TIME
ID,,,,,,,
1,20770,13465959.0,Richmond St E,Parliament St,-79.3640229982,43.6545590111,2007-11-09 05:00:00
2,20771,13467993.0,Lake Shore Blvd W,York St,-79.3808680071,43.6414600022,2007-11-09 05:00:00
3,20772,13444656.0,Steeles Ave W,Carpenter Rd,-79.447588999,43.7920130014,2007-11-09 05:00:00
4,20773,13444138.0,Steeles Ave W,Hilda Ave,-79.4292670009,43.7960070063,2007-11-09 05:00:00
5,20774,13451893.0,Albion Rd,Silverstone Dr,-79.6000939933,43.7429520013,2007-11-09 05:00:00
...,...,...,...,...,...,...,...
190,20959,13445620.0,Steeles Ave W,Alness St,-79.4810569977,43.7847000016,2021-07-29 04:00:00
191,20960,13467918.0,Burnhamthorpe Rd,The West Mall,-79.5672500122,43.6445520063,2021-08-27 04:00:00
192,20961,13464218.0,Jane St,St Clair Ave W,-79.4917669901,43.6671840047,2021-08-16 04:00:00
193,20962,13448022.0,Willowdale Ave,Spring Garden Ave,-79.4009059965,43.7663430021,2021-08-27 04:00:00
194,20963,13448822.0,Markham Rd,Greencedar Crct,-79.2247089903,43.757840005,2021-08-27 04:00:00

In [20]:
red_light.to_csv('red light.csv')